meta_product_name: "takEat easy"
meta_title: "Organiser, Cuisiner, se Régaler: takEat easy!"
meta_description: "teakEat easy: l'application qui simplifie la vie! Laissez vous guider pour CHOISIR les menus de votre semaine, PERSONNALISER les recettes, FAIRE la liste de courses, CUISINER les recettes, pour toute la famille!"
meta_image: "iconFB1200x630.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards